[package]
name = "rustBible"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
# dioxus-desktop = "0.4.3"
# dioxus = { version = "0.4.3" }
dioxus-lib = "0.5.0-alpha.2"
dioxus-web = { version = "0.5.0-alpha.2" }
itertools = "0.12.1"
log = "0.4.21"
manganis = "0.2.1"
reqwest = "0.12.1"
serde = "1.0.197"
serde_json = "1.0.114"
sublime_fuzzy = "0.7.0"
wasm-logger = "0.2.0"
