[package]
name = "rustBible"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.4.3" }
dioxus-logger = "0.4.1"
dioxus-web = { version = "0.4.3" }
log = "0.4.21"
manganis = "0.2.1"
reqwest = "0.12.1"
serde = "1.0.197"
serde_json = "1.0.114"
sublime_fuzzy = "0.7.0"
wasm-logger = "0.2.0"
